version: "3"

services:
  elasticsearch-2.9:
    container_name: elasticsearch-2.9
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data-2.9:/usr/share/elasticsearch/data
    ports:
      - 9202:9200
    networks:
      - ckan-2.9

  publish-2.9:
    image: govuk/publish:latest
    container_name: publish-2.9
    build:
      context: ./src/2.9/datagovuk_publish/
    env_file:
      - .env-2.9
    links:
      - db-2.9:db
      - elasticsearch-2.9:elasticsearch
      - redis-2.9:redis
      - ckan-postdev-2.9:ckan-postdev
    depends_on: 
      - db-2.9
      - elasticsearch-2.9
      - redis-2.9
    command: bash -c "./bin/setup-docker.sh"
    volumes:
      - ./src/2.9/datagovuk_publish:/srv/app/datagovuk_publish
      - ./logs/2.9:/var/log/sidekiq
    networks:
      - ckan-2.9

  find-2.9:
    image: govuk/find:latest
    container_name: find-2.9
    build:
      context: ./src/2.9/datagovuk_find/
    env_file:
      - .env-2.9
    links:
      - elasticsearch-2.9:elasticsearch
    depends_on: 
      - elasticsearch-2.9
    command: bash -c "./bin/setup-docker.sh"
    volumes:
      - ./src/2.9/datagovuk_find:/srv/app/datagovuk_find
      - ./logs/2.9:/var/log/find
    networks:
      - ckan-2.9
    ports:
      - "4002:3000"

volumes:
  es_data-2.9:

networks:
    ckan-2.9:
        driver: bridge
