version: "3"

services:
  ckan-postdev:
    build:
      context: ckan-postdev/
      dockerfile: Dockerfile
      args:
        - TZ=${TZ}
        # set DISABLE_CRON to 1 to disable harvest & pycsw cronjobs (good idea when running tests)
        - DISABLE_CRON=0
        # set START_CKAN to 1 to start ckan and supervisord, 0 to prevent them from starting
        # stopping ckan and background processes can be useful during development to investigate bugs
        - START_CKAN=1
    env_file:
      - .env
    links:
      - db
      - solr
      - redis
    ports:
      - "0.0.0.0:3000:3000"
    volumes:
      - ./src:/srv/app/src_extensions
      - ckan_storage:/var/lib/ckan
      - ./logs:/var/log/ckan
    depends_on: 
      - db
      - solr
      - redis
      - static-mock-harvest-source
    command: bash -c "/srv/app/start_ckan_development.sh"

  db:
    container_name: db
    env_file:
      - .env
    build:
      context: postgresql/
    volumes:
      - pg_data:/var/lib/postgresql/data

  solr:
    container_name: solr
    build:
      context: solr/
    ports:
      - "8983:8983"
    volumes:
      - solr_data:/opt/solr/server/solr/ckan/data/index

  redis:
    container_name: redis
    image: redis:alpine

  nginx:
    container_name: nginx
    build:
      context: nginx/
    links:
      - ckan-postdev
    ports:
      - 0.0.0.0:5000:80
    volumes:
      - ./logs:/var/log/nginx

  static-mock-harvest-source:
    container_name: static-mock-harvest-source
    build:
      context: ./src/ckan-mock-harvest-sources/static/
    ports:
      - "11088:11088"
    volumes:
      - ./src/ckan-mock-harvest-sources/static/responses:/srv/responses
      - ./src/ckan-mock-harvest-sources/static/mock-third-party:/src/mock-third-party

volumes:
  ckan_storage:
  pg_data:
  solr_data:
