version: "3"

services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.9
    environment:
      - node.name=elasticsearch
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - ckan-2.7

  publish:
    image: govuk/publish:2.7
    container_name: publish
    build:
      context: ./src/2.7/datagovuk_publish/
    env_file:
      - .env-2.7
    links:
      - db
      - elasticsearch
      - redis
      - ckan-postdev
    depends_on: 
      - db
      - elasticsearch
      - redis  
    command: bash -c "./bin/setup-docker.sh"
    volumes:
      - ./src/2.7/datagovuk_publish:/srv/app/datagovuk_publish
      - ./logs/2.7:/var/log/sidekiq
    networks:
      - ckan-2.7

volumes:
  es_data:

networks:
    ckan-2.7:
        driver: bridge
