version: "3"

services:
  ckan-postdev:
    build:
      context: ckan-postdev/
      dockerfile: Dockerfile
      args:
        - TZ=${TZ}
    env_file:
      - .env
    links:
      - db
      - solr
      - redis
    ports:
      - "0.0.0.0:3000:3000"
    volumes:
      - ./src:/srv/app/src_extensions
      - ckan_storage:/var/lib/ckan
      - ./logs:/var/log/ckan
    depends_on: 
      - db
      - solr
      - redis
    command: bash -c "/srv/app/start_ckan_development.sh"

  db:
    container_name: db
    env_file:
      - .env
    build:
      context: postgresql/
    volumes:
      - pg_data:/var/lib/postgresql/data

  solr:
    container_name: solr
    build:
      context: solr/
    ports:
      - "8983:8983"
    volumes:
      - solr_data:/opt/solr/server/solr/ckan/data/index

  redis:
    container_name: redis
    image: redis:alpine

  nginx:
    container_name: nginx
    build:
      context: nginx/
    links:
      - ckan-postdev
    ports:
      - 0.0.0.0:5001:80
    volumes:
      - ./logs:/var/log/nginx

volumes:
  ckan_storage:
  pg_data:
  solr_data:
